### ISSUE TITLE
File not saving? Send return code 2

### ISSUE THREAD

**Issue by DanTup** [sillyfrog/RFreplayESP#1]
I combined the send/receive code into the below to troubleshoot why my sends don't work:

```cpp
void loop() {
  Serial.println("\n\nStarting receive...");
  int result = rf433.recordSignal("test");
  if (result == 0) {
    Serial.println("Receive completed successfully!");
  } else {
    Serial.print("Receive errored, no file was written, return code: ");
    Serial.println(result);
  }
  delay(5000);

  Serial.println("\n\nStarting Send...");
   result = rf433.sendSignal("test");
  Serial.print("Complete, return code: ");
  Serial.println(result);
  delay(5000);
}
```

However it seems like the file is somehow not written, since the send code reports a 2 (file not found):

```
Starting receive...
Ready to record: test

Capture Complete. Signal Length: 64
======= Start Signal Below Here ==========
185, 2759, 169, 400, 123, 1404, 161, 361, 169, 1413, 145, 361, 177, 1374, 184, 361, 169, 1374, 184, 346, 192, 1374, 177, 353, 184, 1397, 154, 1404, 146, 384, 161, 369, 161, 1397, 169, 369, 176, 1435, 116, 399, 115, 1412, 162, 2494, 131, 1427, 131, 1965, 69, 1474, 130, 4045, 23, 10952, 77, 1535, 108, 2494, 100, 499, 77, 3008, 93, 
======= End Signal Here ==========
File saved to: /signals/test.txt
Receive completed successfully!


Starting Send...
Complete, return code: 2
```

Since this is all in the same run, I would expect the file that it just wrote to be available. I'm running on a D1 Mini (a cheap one from eBay).

Any ideas how to debug?

**Comment by sillyfrog** [comment]
I use the D1 Mini as well (generally the Pro as the flash is a lot faster for dev work), so it should be OK.

Something I would suggest starting with is doing a `SPIFFS.format()` in the setup. Note that this can can take a *long* time - but may well sort out the issue. The other thing I have found sometimes is the flash just gets confused, so erasing the chip completely and starting again sometimes helps (ie: `esptool.py -p <port> erase_flash`).

The other thing I do is upload a filesystem using the Arduino IDE (or PlatformIO), and tell it to just use 512k or similar to keep it nice and small (fast). Even if it's just one empty file in the data directory to get an initial system underway.

Finally, the last thing you can try is not using this library at all, and use the IRremoteESP8266 library, and when sending, use a frequency of 1 (0 didn't work last I tried). I _think_ this will work for most use cases (providing the signal length is less than half a second). I want to get around to adding support to it for 0Mhz sending for situations such as this as there has been some good work in done in very accurate timing on the capture. I have messed with it, but not used it in earnest, so I maybe wrong and it'll need some real work done to get it working - an idea I have been playing with some sometime.

Good luck!

**Comment by DanTup** [comment]
Thanks for the quick reply! I managed to get up and running by just copy/pasting the timings out into my own loop and using `digitalWrite` (so using this library just for the capturing) and that seemed to work fine with my testing. I've gone and broken things will moving from breadboard to soldered wires though, so will need to do some more debugging before I can try this (though tbh I may just stick with the manual loop since there's less to go wrong).

If I do get chance to try it out I'll let you know, but otherwise feel free to close this if there's not much you can do (I guess it's not a bug in your library if SPIFFS or my chip aren't working correctly).

Thanks for your library anyway - I spend hours trying to get rc-switch working today with no luck (I guess it didn't recognise the protocol) but after finding yours I was able to capture within a few minutes (even though it took a little longer to replay!). 👍

**Comment by sillyfrog** [comment]
Sweet, glad it worked. 

The other thing using SPIFFS does is save on program memory. I used to save the files on my PC, and upload (via the data directory) when using a new chip. But only an issue I guess if you have a number of captures. 

Good luck!
