### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by joroMaser** [sillyfrog/RFreplayESP#2]
https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md#file-system-object-spiffs in README return 404

By the way, how can I contact with you?

**Comment by sillyfrog** [comment]
Thanks, I have updated.

I have a "contact repo" here: https://github.com/sillyfrog/contact/issues where you can raise an issue.

If it's more private, let me know and I can email you directly via GitHub.

Cheers.
