### ISSUE TITLE
Antena for FS1000A

### ISSUE THREAD

**Issue by joroMaser** [sillyfrog/RFreplayESP#3]
Do you use FS1000A with antena?
Can you tell please which antena did you connect?  What was the range of TX?

**Comment by sillyfrog** [comment]
I don't have an extra antenna on the FS1000A, it's just like the one in the photo at https://github.com/sillyfrog/RFreplayESP/wiki (ie: no additional antenna).

I'm not going for a super long range, I just use several of them for different things. I'm getting about 10m reliably at the moment, through a couple of walls, and using it to control "BOFO" roller blind motors - see image below. But driving them using another project: https://github.com/sillyfrog/homie_blind_control 

![1set-Motor-Tubular-12V-Electric-Curtains-Roller-DIY-Electric-Roller-Blind-Motor-Kit-with-Remote-Controller](https://user-images.githubusercontent.com/816454/148476264-be7e0ab5-8f6b-4961-bc27-2b1182a5f4cd.jpg)
